schema_version = "1.0.0"

id = "trackcompiler"
version = "0.2.0"
name = "OMTT TrackCompiler"
tagline = "An open-source toolkit for Madness Engine track development"
maintainer = "ohyeah2389"
type = "add-on"
tags = ["Import-Export", "Pipeline"]
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.0.0"

platforms = ["windows-x64"]

[permissions]
files = "Export of Madness Engine track files"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "*.pyc",
  ".*",
]
